"""add_platform_specific_fields

Revision ID: e31ae7503220
Revises: 5281f36d8f00
Create Date: 2025-05-24 17:49:16.572862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e31ae7503220'
down_revision: Union[str, None] = '5281f36d8f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('platform_credentials', sa.Column('platform_data', sa.JSON(), nullable=True))
    op.add_column('platform_credentials', sa.Column('publication_id', sa.String(), nullable=True))
    op.add_column('platform_credentials', sa.Column('platform_user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('platform_credentials', 'platform_user_id')
    op.drop_column('platform_credentials', 'publication_id')
    op.drop_column('platform_credentials', 'platform_data')
    # ### end Alembic commands ###
